services:
  bot:
    image: localhost:5000/fysm-randomizer-bot:latest
    restart: always
    command: bash -c "uv run migrate.py && uv run polling.py"
    depends_on:
      - redis
    env_file:
      - ./.env
    volumes:
      - ./data:/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel debug --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
    volumes:
      - fysm-randomizer-redis-data:/data

volumes:
  fysm-randomizer-redis-data:
