services:
  bot:
    container_name: bot
    restart: always
    build: ./
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; uv run ./bot/infra/db/migrate.py && uv run ./bot/telegram/polling.py"
    depends_on:
      - redis
    env_file:
      - ./.env

  postgres:
    image: postgres:18.0
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - fysm-randomizer-pg-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel debug --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - fysm-randomizer-redis-data:/data

volumes:
  fysm-randomizer-pg-data:
  fysm-randomizer-redis-data:
