version: '3.8'

services:
  bot:
    image: localhost:5000/fysm-randomizer-bot:latest
    networks:
      - fysm-randomizer-net
    command: bash -c "python polling.py"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints:
          - node.hostname == node

  redis:
    image: redis:alpine
    networks:
      - fysm-randomizer-net
    ports:
      - "6379"
    command: redis-server --save 20 1 --loglevel debug --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
    volumes:
      - fysm-randomizer-redis-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == node

volumes:
  fysm-randomizer-pg-data:
  fysm-randomizer-redis-data:
networks:
  fysm-randomizer-net:
    external: false
    name: fysm-randomizer-net
