from enum import Enum


class ChatActionEnum(str, Enum):
    TYPING = "TYPING"
    UPLOAD_PHOTO = "UPLOAD_PHOTO"
    UPLOAD_VIDEO = "UPLOAD_VIDEO"
    UPLOAD_AUDIO = "UPLOAD_AUDIO"
    UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT"
    FIND_LOCATION = "FIND_LOCATION"
    RECORD_VIDEO = "RECORD_VIDEO"
