"""Add mailing table

Revision ID: cc20fa03fa1e
Revises: 82594823b648
Create Date: 2025-05-08 22:34:29.637733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc20fa03fa1e'
down_revision: Union[str, None] = '82594823b648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True, comment='Название рассылки (для админа)'),
    sa.Column('text', sa.Text(), nullable=True, comment='Текст рассылки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailing_id'), 'mailing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailing_id'), table_name='mailing')
    op.drop_table('mailing')
    # ### end Alembic commands ###
